### ISSUE TITLE
[test] pouch testing subtasks

### ISSUE THREAD

**Issue by sunyuan3** [alibaba/pouch#50]
**Issue Description**
This issue is to track the progress of pouch testing tasks.
- [x] pouch installation testing script in local environment: https://github.com/alibaba/pouch/pull/86
- [x] pouch installation testing in CI: https://github.com/alibaba/pouch/pull/86
- [x] pouch integration testing framework:https://github.com/alibaba/pouch/pull/98
- [ ] performance testing(pouch vs docker)
- [x] Add godoc in README.md:https://github.com/alibaba/pouch/pull/109
- [x] Add https://travis-ci.com/alibaba/pouch in README.md:https://github.com/alibaba/pouch/pull/109
- [x] Add https://app.fossa.io in README.md:https://github.com/alibaba/pouch/pull/109
- [x] Add https://goreportcard.com in README.md:https://github.com/alibaba/pouch/pull/109
- [x] Add integration testing guideline:https://github.com/alibaba/pouch/pull/114

**Describe what happened**:
None
**Describe what you expected to happen**:
None
**How to reproduce it (as minimally and precisely as possible)**:
None
**Anything else we need to know?**:
No
**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
Any update on this? @sunyuan3

**Comment by allencloud** [comment]
I think we can close this, when we released, we can add a separated issue to track performance testing...
