### ISSUE TITLE
[enhancement request] Advanced configuration for Sandbox and Container in CRI

### ISSUE THREAD

**Issue by YaoZengzeng** [alibaba/pouch#635]
### Sandbox related

- [x] Sysctl configuration for sandbox #654 
- [x] DNS configuration for sandbox #912 
- [x] Port mapping configuration for sandbox #730 

### Container related

- [x] Basic volume and device adding for container #717 
- [x] Mount propagation support for container #717 
- [x] AppArmor support for container #672 
- [x] Capabilities setting for container #680 
- [x] NoNewPrivs support container #935 

### Sandbox & Container Both

- [x] Namespace option for sandbox & container #753 
- [x] Supplemental Group support for sandbox & container #753 
- [x] RunAsUser support for sandbox & container #722 
- [x] RunAsUserName support for sandbox & container
- [x] ReadOnlyRootfs support for sandbox & container #935 
- [x] Privileged mode support for sandbox & container #691 
- [x] Seccomp support for sandbox & container #701 
- [x] SELinux support for sandbox & container

### NOTE

The list may not be complete yet, we should supplement it anytime as the development going on :)

cc @allencloud

**Comment by allencloud** [comment]
Any update on this ? @YaoZengzeng

**Comment by allencloud** [comment]
Do we finish `RunAsUserName support for sandbox & container` and `SELinux support for sandbox & container`?

If the answer is yes, please close this issue. Thanks. @YaoZengzeng @Starnop

**Comment by YaoZengzeng** [comment]
All tasks have been finished, close now.
